# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup NODE.JS
      - name: Setup node js
        uses: actions/setup-node@v2
        with: 
          node-version: ${{matrix.node-version}}
      
      # Instalando as dependencias
      - run: npm install
      
      # Executar os testes usando o Cucumber
      - run: npm run cy:run:cucumber
        continue-on-error: true
      
      # Gerar o relatorio
      - run: npm run report:cucumber
        continue-on-error: true
        
      # Publicar relatorio em HTML
      - name: Deploy to GithubPages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: cypress/reports
          
        
